version: '3.8'

services:
  mongo_example:
    image: mongo:latest
    container_name: mongo_example
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arthur
      - MONGO_INITDB_ROOT_PASSWORD=arthur
      - MONGO_INITDB_DATABASE=admin
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge