version: '3.8'

services:
# short syntax
  mongobind1:
    image: mongo:latest
    container_name: mongobind1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arthur
      - MONGO_INITDB_ROOT_PASSWORD=arthur
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - "./data-mongo1:/data/db"
# long syntax
  mongobind2:
    image: mongo:latest
    container_name: mongobind2
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arthur
      - MONGO_INITDB_ROOT_PASSWORD=arthur
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - type: bind
        source: "./data-mongo2"
        target: "/data/db"
        read_only: false