version: '3.9'

services:
  app:
    container_name: app
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "app-golang:1.0.3"
    ports:
      - "8080:8080"
    environment:
      - "APP_PORT=8080"